import type { CuratedTool } from "@/lib/types";

export const CURATED_TOOLS: CuratedTool[] = [
  // ── AI MODELS ──────────────────────────────────────────────────────────────
  {
    slug: "claude",
    name: "Claude",
    description: "Anthropic's family of AI assistants — Claude 3.5 Sonnet, Opus, and Haiku — excelling at reasoning, coding, and analysis.",
    githubOwner: "anthropics",
    githubRepo: "anthropic-sdk-python",
    websiteUrl: "https://claude.ai",
    categories: ["ai-models"],
    featured: true,
  },
  {
    slug: "gpt-4o",
    name: "GPT-4o",
    description: "OpenAI's flagship multimodal model — text, vision, and audio in one. Powers ChatGPT and the Assistants API.",
    githubOwner: "openai",
    githubRepo: "openai-python",
    websiteUrl: "https://openai.com",
    categories: ["ai-models"],
    featured: true,
  },
  {
    slug: "gemini",
    name: "Gemini",
    description: "Google DeepMind's multimodal model series. Gemini 2.0 Flash and Pro lead on long-context and reasoning tasks.",
    githubOwner: "google-gemini",
    githubRepo: "generative-ai-python",
    websiteUrl: "https://gemini.google.com",
    categories: ["ai-models"],
    featured: true,
  },
  {
    slug: "llama",
    name: "Llama",
    description: "Meta's open-weight LLM family. Llama 3.3 70B rivals closed models on many benchmarks and runs locally.",
    githubOwner: "meta-llama",
    githubRepo: "llama",
    websiteUrl: "https://llama.meta.com",
    categories: ["ai-models"],
    featured: true,
  },
  {
    slug: "mistral",
    name: "Mistral AI",
    description: "European AI lab building frontier open and proprietary models. Mistral Large 2 and Mixtral MoE are widely deployed.",
    githubOwner: "mistralai",
    githubRepo: "mistral-common",
    websiteUrl: "https://mistral.ai",
    categories: ["ai-models"],
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    description: "Chinese AI lab's open-source models — DeepSeek V3 and R1 match GPT-4-class on coding and math at a fraction of cost.",
    githubOwner: "deepseek-ai",
    githubRepo: "DeepSeek-V3",
    websiteUrl: "https://deepseek.com",
    categories: ["ai-models"],
    featured: true,
  },
  {
    slug: "grok",
    name: "Grok",
    description: "xAI's large language model with real-time X/Twitter data access and a uniquely witty personality.",
    githubOwner: "xai-org",
    githubRepo: "grok-1",
    websiteUrl: "https://x.ai/grok",
    categories: ["ai-models"],
  },
  {
    slug: "gemma",
    name: "Gemma",
    description: "Google's family of lightweight open models designed for on-device and low-latency inference.",
    githubOwner: "google",
    githubRepo: "gemma_pytorch",
    websiteUrl: "https://ai.google.dev/gemma",
    categories: ["ai-models"],
  },
  {
    slug: "qwen",
    name: "Qwen",
    description: "Alibaba Cloud's open-source LLM series. Qwen2.5-72B and Qwen-Coder deliver top benchmark scores across sizes.",
    githubOwner: "QwenLM",
    githubRepo: "Qwen2.5",
    websiteUrl: "https://qwenlm.github.io",
    categories: ["ai-models"],
  },
  {
    slug: "phi",
    name: "Phi",
    description: "Microsoft's small language models — Phi-4 achieves GPT-4 quality at a fraction of the parameters.",
    githubOwner: "microsoft",
    githubRepo: "PhiCookBook",
    websiteUrl: "https://azure.microsoft.com/en-us/products/phi",
    categories: ["ai-models"],
  },

  // ── AI CODING TOOLS ────────────────────────────────────────────────────────
  {
    slug: "cursor",
    name: "Cursor",
    description: "AI-first code editor built on VS Code. Tab completion, multi-file edits, and chat with your codebase.",
    websiteUrl: "https://cursor.com",
    githubOwner: "getcursor",
    githubRepo: "cursor",
    categories: ["ai-coding"],
    featured: true,
  },
  {
    slug: "windsurf",
    name: "Windsurf",
    description: "Codeium's agentic IDE — Cascade agents autonomously plan, edit, and run multi-step coding tasks.",
    websiteUrl: "https://codeium.com/windsurf",
    categories: ["ai-coding"],
    featured: true,
  },
  {
    slug: "claude-code",
    name: "Claude Code",
    description: "Anthropic's agentic CLI coding tool — reads your repo, writes code, runs tests, and submits PRs.",
    githubOwner: "anthropics",
    githubRepo: "claude-code",
    websiteUrl: "https://claude.ai/code",
    categories: ["ai-coding"],
    featured: true,
  },
  {
    slug: "aider",
    name: "aider",
    description: "AI pair programming in your terminal. Works with any git repo — edit multiple files, run tests, commit automatically.",
    githubOwner: "Aider-AI",
    githubRepo: "aider",
    websiteUrl: "https://aider.chat",
    categories: ["ai-coding"],
    featured: true,
  },
  {
    slug: "continue",
    name: "Continue",
    description: "Open-source VS Code and JetBrains extension connecting any LLM for autocomplete, chat, and edits.",
    githubOwner: "continuedev",
    githubRepo: "continue",
    websiteUrl: "https://continue.dev",
    categories: ["ai-coding"],
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    description: "Microsoft's AI pair programmer integrated into VS Code, JetBrains, and the terminal. Powered by OpenAI Codex.",
    websiteUrl: "https://github.com/features/copilot",
    githubOwner: "github",
    githubRepo: "copilot-docs",
    categories: ["ai-coding"],
    featured: true,
  },
  {
    slug: "cody",
    name: "Cody",
    description: "Sourcegraph's AI coding assistant with enterprise codebase awareness and multi-repo context.",
    githubOwner: "sourcegraph",
    githubRepo: "cody",
    websiteUrl: "https://sourcegraph.com/cody",
    categories: ["ai-coding"],
  },
  {
    slug: "codeium",
    name: "Codeium",
    description: "Free AI coding toolkit — autocomplete, search, and chat across 70+ languages and 40+ editors.",
    githubOwner: "Exafunction",
    githubRepo: "codeium.vim",
    websiteUrl: "https://codeium.com",
    categories: ["ai-coding"],
  },
  {
    slug: "amazon-q",
    name: "Amazon Q Developer",
    description: "AWS's AI coding assistant for generating, debugging, and transforming code in VS Code and JetBrains.",
    websiteUrl: "https://aws.amazon.com/q/developer",
    githubOwner: "aws",
    githubRepo: "aws-toolkit-vscode",
    categories: ["ai-coding"],
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    description: "Privacy-focused AI code completion that runs locally or in the cloud. Works in all major IDEs.",
    websiteUrl: "https://www.tabnine.com",
    githubOwner: "codota",
    githubRepo: "tabnine-vscode",
    categories: ["ai-coding"],
  },

  // ── EDITORS & IDEs ─────────────────────────────────────────────────────────
  {
    slug: "vscode",
    name: "VS Code",
    description: "Microsoft's open-source code editor — the world's most popular IDE with an unmatched extension ecosystem.",
    githubOwner: "microsoft",
    githubRepo: "vscode",
    websiteUrl: "https://code.visualstudio.com",
    categories: ["editors"],
    featured: true,
  },
  {
    slug: "neovim",
    name: "Neovim",
    description: "Hyperextensible Vim-based text editor with Lua scripting, built-in LSP, and a thriving plugin ecosystem.",
    githubOwner: "neovim",
    githubRepo: "neovim",
    brewName: "neovim",
    categories: ["editors"],
    featured: true,
  },
  {
    slug: "zed",
    name: "Zed",
    description: "High-performance multiplayer code editor built in Rust. GPU-accelerated, collaborative, AI-first.",
    githubOwner: "zed-industries",
    githubRepo: "zed",
    websiteUrl: "https://zed.dev",
    categories: ["editors"],
    featured: true,
  },
  {
    slug: "helix",
    name: "Helix",
    description: "Post-modern modal text editor in Rust with built-in LSP, multi-cursor, and tree-sitter highlighting.",
    githubOwner: "helix-editor",
    githubRepo: "helix",
    brewName: "helix",
    categories: ["editors"],
  },
  {
    slug: "jetbrains",
    name: "JetBrains IDEs",
    description: "Suite of professional IDEs — IntelliJ IDEA, PyCharm, WebStorm, GoLand — with deep language understanding.",
    githubOwner: "JetBrains",
    githubRepo: "intellij-community",
    websiteUrl: "https://www.jetbrains.com",
    categories: ["editors"],
  },
  {
    slug: "vim",
    name: "Vim",
    description: "The ubiquitous modal editor. Available on every Unix system, infinitely customizable, never slow.",
    githubOwner: "vim",
    githubRepo: "vim",
    brewName: "vim",
    categories: ["editors"],
  },
  {
    slug: "emacs",
    name: "Emacs",
    description: "The extensible, self-documenting text editor. With Doom or Spacemacs, a fully-featured development environment.",
    githubOwner: "emacs-mirror",
    githubRepo: "emacs",
    brewName: "emacs",
    categories: ["editors"],
  },
  {
    slug: "lapce",
    name: "Lapce",
    description: "Lightning-fast open-source code editor written in Rust with native GPU rendering and remote development support.",
    githubOwner: "lapce",
    githubRepo: "lapce",
    websiteUrl: "https://lapce.dev",
    categories: ["editors"],
  },

  // ── TERMINALS ──────────────────────────────────────────────────────────────
  {
    slug: "warp",
    name: "Warp",
    description: "The modern terminal with AI command suggestions, collaborative notebooks, and teams sharing — built in Rust.",
    websiteUrl: "https://warp.dev",
    githubOwner: "warpdotdev",
    githubRepo: "Warp",
    categories: ["terminals"],
    featured: true,
  },
  {
    slug: "iterm2",
    name: "iTerm2",
    description: "The macOS terminal replacement — split panes, search, autocomplete, triggers, and rich scripting API.",
    githubOwner: "gnachman",
    githubRepo: "iTerm2",
    websiteUrl: "https://iterm2.com",
    brewName: "iterm2",
    categories: ["terminals"],
    featured: true,
  },
  {
    slug: "ghostty",
    name: "Ghostty",
    description: "Fast, feature-rich terminal emulator by Mitchell Hashimoto. Native macOS and Linux, GPU-accelerated.",
    githubOwner: "ghostty-org",
    githubRepo: "ghostty",
    websiteUrl: "https://ghostty.org",
    brewName: "ghostty",
    categories: ["terminals"],
    featured: true,
  },
  {
    slug: "alacritty",
    name: "Alacritty",
    description: "The fastest terminal emulator in existence — OpenGL-accelerated, zero-latency, cross-platform.",
    githubOwner: "alacritty",
    githubRepo: "alacritty",
    brewName: "alacritty",
    categories: ["terminals"],
  },
  {
    slug: "kitty",
    name: "kitty",
    description: "GPU-based terminal emulator with tiling layouts, unicode support, and a powerful scripting protocol.",
    githubOwner: "kovidgoyal",
    githubRepo: "kitty",
    brewName: "kitty",
    categories: ["terminals"],
  },
  {
    slug: "wezterm",
    name: "WezTerm",
    description: "GPU-accelerated cross-platform terminal emulator and multiplexer with Lua configuration.",
    githubOwner: "wez",
    githubRepo: "wezterm",
    brewName: "wezterm",
    categories: ["terminals"],
  },
  {
    slug: "hyper",
    name: "Hyper",
    description: "Electron-based terminal built on web technologies — extensible with npm packages.",
    githubOwner: "vercel",
    githubRepo: "hyper",
    websiteUrl: "https://hyper.is",
    categories: ["terminals"],
  },

  // ── SHELLS ─────────────────────────────────────────────────────────────────
  {
    slug: "oh-my-zsh",
    name: "Oh My Zsh",
    description: "The community-driven framework for managing Zsh configuration — 300+ plugins, 150+ themes.",
    githubOwner: "ohmyzsh",
    githubRepo: "ohmyzsh",
    websiteUrl: "https://ohmyz.sh",
    categories: ["shells"],
    featured: true,
  },
  {
    slug: "powerlevel10k",
    name: "Powerlevel10k",
    description: "Blazing fast Zsh theme with a config wizard. Git status, time, battery, and 40+ prompt segments.",
    githubOwner: "romkatv",
    githubRepo: "powerlevel10k",
    categories: ["shells"],
  },
  {
    slug: "fish",
    name: "fish",
    description: "User-friendly command line shell with autosuggestions, tab completions, and web-based configuration.",
    githubOwner: "fish-shell",
    githubRepo: "fish-shell",
    brewName: "fish",
    categories: ["shells"],
  },
  {
    slug: "nushell",
    name: "nushell",
    description: "A new type of shell that treats data as structured tables — pipelines that understand JSON, CSV, YAML.",
    githubOwner: "nushell",
    githubRepo: "nushell",
    brewName: "nushell",
    categories: ["shells"],
  },
  {
    slug: "zsh",
    name: "Zsh",
    description: "Extended Bourne shell with scripting improvements, themes, and plugin support via frameworks like Oh My Zsh.",
    githubOwner: "zsh-users",
    githubRepo: "zsh",
    websiteUrl: "https://www.zsh.org",
    categories: ["shells"],
  },
  {
    slug: "starship",
    name: "starship",
    description: "The minimal, blazing-fast cross-shell prompt — works with Zsh, Bash, Fish, PowerShell, and more.",
    githubOwner: "starship",
    githubRepo: "starship",
    brewName: "starship",
    categories: ["shells"],
    featured: true,
  },
  {
    slug: "zoxide",
    name: "zoxide",
    description: "A smarter cd command — learns your habits and jumps to frequently visited directories.",
    githubOwner: "ajeetdsouza",
    githubRepo: "zoxide",
    brewName: "zoxide",
    categories: ["shells"],
  },
  {
    slug: "atuin",
    name: "atuin",
    description: "Magical shell history — syncs across machines, full-text search, per-command stats.",
    githubOwner: "atuinsh",
    githubRepo: "atuin",
    brewName: "atuin",
    categories: ["shells"],
  },
  {
    slug: "tmux",
    name: "tmux",
    description: "Terminal multiplexer — persistent sessions, split panes, and scriptable window management.",
    githubOwner: "tmux",
    githubRepo: "tmux",
    brewName: "tmux",
    categories: ["shells"],
  },
  {
    slug: "zellij",
    name: "zellij",
    description: "A terminal workspace with batteries included — tabs, panes, plugins, and floating windows.",
    githubOwner: "zellij-org",
    githubRepo: "zellij",
    brewName: "zellij",
    categories: ["shells"],
  },

  // ── VERSION CONTROL PLATFORMS ──────────────────────────────────────────────
  {
    slug: "github",
    name: "GitHub",
    description: "The world's largest code hosting platform — 100M+ developers, Actions CI/CD, Copilot, and Codespaces.",
    githubOwner: "github",
    githubRepo: "docs",
    websiteUrl: "https://github.com",
    categories: ["version-control"],
    featured: true,
  },
  {
    slug: "gitlab",
    name: "GitLab",
    description: "Complete DevSecOps platform — self-hosted or SaaS, with CI/CD, security scanning, and container registry.",
    githubOwner: "gitlabhq",
    githubRepo: "gitlabhq",
    websiteUrl: "https://gitlab.com",
    categories: ["version-control"],
    featured: true,
  },
  {
    slug: "gitea",
    name: "Gitea",
    description: "Lightweight self-hosted Git service — painless to set up, runs on a Raspberry Pi, MIT licensed.",
    githubOwner: "go-gitea",
    githubRepo: "gitea",
    websiteUrl: "https://gitea.io",
    brewName: "gitea",
    categories: ["version-control"],
  },
  {
    slug: "forgejo",
    name: "Forgejo",
    description: "Self-hosted lightweight software forge — community fork of Gitea, fully open source.",
    githubOwner: "forgejo",
    githubRepo: "forgejo",
    websiteUrl: "https://forgejo.org",
    categories: ["version-control"],
  },
  {
    slug: "bitbucket",
    name: "Bitbucket",
    description: "Atlassian's Git solution with native Jira integration, Pipelines CI/CD, and enterprise access controls.",
    websiteUrl: "https://bitbucket.org",
    categories: ["version-control"],
  },

  // ── HOSTING & CLOUD ────────────────────────────────────────────────────────
  {
    slug: "vercel",
    name: "Vercel",
    description: "The frontend cloud — instant deployments, Edge Network, serverless functions, and the home of Next.js.",
    githubOwner: "vercel",
    githubRepo: "vercel",
    websiteUrl: "https://vercel.com",
    categories: ["hosting"],
    featured: true,
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    description: "Global network platform — CDN, DDoS protection, Workers serverless, R2 storage, and D1 database.",
    githubOwner: "cloudflare",
    githubRepo: "workers-sdk",
    websiteUrl: "https://cloudflare.com",
    categories: ["hosting"],
    featured: true,
  },
  {
    slug: "supabase",
    name: "Supabase",
    description: "Open-source Firebase alternative — Postgres database, Auth, Storage, Edge Functions, and Realtime.",
    githubOwner: "supabase",
    githubRepo: "supabase",
    websiteUrl: "https://supabase.com",
    categories: ["hosting"],
    featured: true,
  },
  {
    slug: "railway",
    name: "Railway",
    description: "Instant deployment platform — deploy any app from GitHub in seconds, with databases and networking built in.",
    githubOwner: "railwayapp",
    githubRepo: "cli",
    websiteUrl: "https://railway.app",
    categories: ["hosting"],
  },
  {
    slug: "fly-io",
    name: "Fly.io",
    description: "Run applications close to users worldwide — Firecracker VMs, Postgres, Redis, and global Anycast networking.",
    githubOwner: "superfly",
    githubRepo: "flyctl",
    websiteUrl: "https://fly.io",
    brewName: "flyctl",
    categories: ["hosting"],
  },
  {
    slug: "render",
    name: "Render",
    description: "Unified cloud to build and run apps — web services, cron jobs, static sites, and managed databases.",
    websiteUrl: "https://render.com",
    categories: ["hosting"],
  },
  {
    slug: "netlify",
    name: "Netlify",
    description: "Platform for web projects — instant git-based deployments, Edge Functions, Forms, and Split Testing.",
    githubOwner: "netlify",
    githubRepo: "cli",
    websiteUrl: "https://netlify.com",
    brewName: "netlify-cli",
    categories: ["hosting"],
  },
  {
    slug: "neon-db",
    name: "Neon",
    description: "Serverless Postgres — autoscaling, branching, bottomless storage, and instant provisioning.",
    githubOwner: "neondatabase",
    githubRepo: "neon",
    websiteUrl: "https://neon.tech",
    categories: ["hosting"],
    featured: true,
  },
  {
    slug: "aws",
    name: "AWS",
    description: "Amazon Web Services — the world's largest cloud platform with 200+ services spanning compute, storage, ML, and more.",
    githubOwner: "aws",
    githubRepo: "aws-cli",
    websiteUrl: "https://aws.amazon.com",
    brewName: "awscli",
    categories: ["hosting"],
    featured: true,
  },
  {
    slug: "gcp",
    name: "Google Cloud",
    description: "Google's cloud platform — BigQuery, Kubernetes Engine, Cloud Run, Vertex AI, and global fiber network.",
    githubOwner: "GoogleCloudPlatform",
    githubRepo: "cloud-code-vscode",
    websiteUrl: "https://cloud.google.com",
    categories: ["hosting"],
  },
  {
    slug: "azure",
    name: "Azure",
    description: "Microsoft's cloud — hybrid cloud, enterprise Azure AD, Azure OpenAI Service, and extensive compliance certifications.",
    githubOwner: "Azure",
    githubRepo: "azure-cli",
    websiteUrl: "https://azure.microsoft.com",
    brewName: "azure-cli",
    categories: ["hosting"],
  },
  {
    slug: "digitalocean",
    name: "DigitalOcean",
    description: "Developer-friendly cloud — Droplets, Managed Kubernetes, App Platform, and predictable pricing.",
    githubOwner: "digitalocean",
    githubRepo: "doctl",
    websiteUrl: "https://digitalocean.com",
    brewName: "doctl",
    categories: ["hosting"],
  },
  {
    slug: "hetzner",
    name: "Hetzner",
    description: "German cloud and hosting provider — excellent price-performance ratio, popular with European developers.",
    websiteUrl: "https://www.hetzner.com",
    categories: ["hosting"],
  },
  {
    slug: "planetscale",
    name: "PlanetScale",
    description: "MySQL-compatible serverless database with branching workflow, non-blocking schema changes, and global replication.",
    githubOwner: "planetscale",
    githubRepo: "cli",
    websiteUrl: "https://planetscale.com",
    categories: ["hosting"],
  },

  // ── CONTAINERS ─────────────────────────────────────────────────────────────
  {
    slug: "docker",
    name: "Docker",
    description: "The container platform standard — build, share, and run containerized applications anywhere.",
    githubOwner: "moby",
    githubRepo: "moby",
    websiteUrl: "https://docker.com",
    categories: ["containers"],
    featured: true,
  },
  {
    slug: "orbstack",
    name: "OrbStack",
    description: "Fast, light, and simple Docker Desktop alternative for macOS — containers and Linux VMs in seconds.",
    githubOwner: "orbstack",
    githubRepo: "orbstack",
    websiteUrl: "https://orbstack.dev",
    brewName: "orbstack",
    categories: ["containers"],
    featured: true,
  },
  {
    slug: "podman",
    name: "Podman",
    description: "Daemonless container engine — rootless, OCI-compliant, and a drop-in Docker replacement.",
    githubOwner: "containers",
    githubRepo: "podman",
    brewName: "podman",
    categories: ["containers"],
  },
  {
    slug: "colima",
    name: "Colima",
    description: "Container runtimes on macOS with minimal setup — Docker, containerd, and Kubernetes in one CLI.",
    githubOwner: "abiosoft",
    githubRepo: "colima",
    brewName: "colima",
    categories: ["containers"],
  },
  {
    slug: "lazydocker",
    name: "lazydocker",
    description: "The lazier way to manage everything docker — terminal UI for containers, images, volumes, and networks.",
    githubOwner: "jesseduffield",
    githubRepo: "lazydocker",
    brewName: "lazydocker",
    categories: ["containers"],
  },
  {
    slug: "dive",
    name: "dive",
    description: "A tool for exploring each layer in a Docker image — find what's bloating your image.",
    githubOwner: "wagoodman",
    githubRepo: "dive",
    brewName: "dive",
    categories: ["containers"],
  },
  {
    slug: "rancher-desktop",
    name: "Rancher Desktop",
    description: "Open-source Docker Desktop alternative — Kubernetes, container management, and nerdctl on macOS/Linux/Windows.",
    githubOwner: "rancher-sandbox",
    githubRepo: "rancher-desktop",
    websiteUrl: "https://rancherdesktop.io",
    categories: ["containers"],
  },

  // ── KUBERNETES ─────────────────────────────────────────────────────────────
  {
    slug: "k9s",
    name: "k9s",
    description: "Kubernetes CLI To Manage Your Clusters In Style — terminal UI with real-time resource monitoring.",
    githubOwner: "derailed",
    githubRepo: "k9s",
    brewName: "k9s",
    categories: ["kubernetes"],
    featured: true,
  },
  {
    slug: "helm",
    name: "Helm",
    description: "The Kubernetes package manager — define, install, and upgrade complex applications with charts.",
    githubOwner: "helm",
    githubRepo: "helm",
    brewName: "helm",
    categories: ["kubernetes"],
    featured: true,
  },
  {
    slug: "argo-cd",
    name: "Argo CD",
    description: "Declarative GitOps continuous delivery for Kubernetes — sync your cluster state from Git.",
    githubOwner: "argoproj",
    githubRepo: "argo-cd",
    categories: ["kubernetes"],
    featured: true,
  },
  {
    slug: "flux",
    name: "Flux",
    description: "GitOps toolkit for Kubernetes — continuous delivery from Git, Helm, and OCI registries.",
    githubOwner: "fluxcd",
    githubRepo: "flux2",
    brewName: "fluxcd/tap/flux",
    categories: ["kubernetes"],
  },
  {
    slug: "lens",
    name: "Lens",
    description: "The Kubernetes IDE — visual cluster management, metrics, and multi-cluster support.",
    githubOwner: "lensapp",
    githubRepo: "lens",
    websiteUrl: "https://k8slens.dev",
    categories: ["kubernetes"],
  },
  {
    slug: "tilt",
    name: "Tilt",
    description: "Dev environment as code — live-updates containers as you save files, instant feedback loop.",
    githubOwner: "tilt-dev",
    githubRepo: "tilt",
    brewName: "tilt-dev/tap/tilt",
    categories: ["kubernetes"],
  },
  {
    slug: "minikube",
    name: "minikube",
    description: "Local Kubernetes — run a full cluster on your laptop for development and testing.",
    githubOwner: "kubernetes",
    githubRepo: "minikube",
    brewName: "minikube",
    categories: ["kubernetes"],
  },
  {
    slug: "k3s",
    name: "k3s",
    description: "Lightweight Kubernetes — 5-less than k8s, certified, perfect for IoT, edge, and CI environments.",
    githubOwner: "k3s-io",
    githubRepo: "k3s",
    websiteUrl: "https://k3s.io",
    categories: ["kubernetes"],
  },

  // ── GIT CLI TOOLS ──────────────────────────────────────────────────────────
  {
    slug: "lazygit",
    name: "lazygit",
    description: "Simple terminal UI for git commands — stage hunks, rebase, cherry-pick, and resolve conflicts visually.",
    githubOwner: "jesseduffield",
    githubRepo: "lazygit",
    brewName: "lazygit",
    categories: ["git"],
    featured: true,
  },
  {
    slug: "delta",
    name: "delta",
    description: "A syntax-highlighting pager for git, diff, grep, and blame output.",
    githubOwner: "dandavison",
    githubRepo: "delta",
    brewName: "git-delta",
    categories: ["git"],
  },
  {
    slug: "gh",
    name: "gh",
    description: "GitHub's official command line tool — create PRs, manage issues, and interact with Actions from the terminal.",
    githubOwner: "cli",
    githubRepo: "cli",
    brewName: "gh",
    categories: ["git"],
    featured: true,
  },
  {
    slug: "gitui",
    name: "gitui",
    description: "Blazing fast terminal UI for git written in Rust.",
    githubOwner: "gitui-org",
    githubRepo: "gitui",
    brewName: "gitui",
    categories: ["git"],
  },
  {
    slug: "tig",
    name: "tig",
    description: "Text-mode interface for git — browse commits, diffs, and file history without leaving the terminal.",
    githubOwner: "jonas",
    githubRepo: "tig",
    brewName: "tig",
    categories: ["git"],
  },

  // ── PACKAGE MANAGERS ───────────────────────────────────────────────────────
  {
    slug: "bun",
    name: "Bun",
    description: "All-in-one JavaScript runtime and toolkit — package manager, bundler, test runner, built in Zig.",
    githubOwner: "oven-sh",
    githubRepo: "bun",
    websiteUrl: "https://bun.sh",
    categories: ["package-managers"],
    featured: true,
  },
  {
    slug: "pnpm",
    name: "pnpm",
    description: "Fast, disk space efficient package manager — symlinks to a content-addressable store, strict by default.",
    githubOwner: "pnpm",
    githubRepo: "pnpm",
    websiteUrl: "https://pnpm.io",
    brewName: "pnpm",
    categories: ["package-managers"],
    featured: true,
  },
  {
    slug: "mise",
    name: "mise",
    description: "Dev tools manager — manage runtime versions (Node, Python, Go) and env vars per project directory.",
    githubOwner: "jdx",
    githubRepo: "mise",
    websiteUrl: "https://mise.jdx.dev",
    brewName: "mise",
    categories: ["package-managers"],
    featured: true,
  },
  {
    slug: "nix",
    name: "Nix",
    description: "Purely functional package manager — reproducible builds, atomic upgrades, and rollbacks.",
    githubOwner: "NixOS",
    githubRepo: "nix",
    websiteUrl: "https://nixos.org",
    categories: ["package-managers"],
  },
  {
    slug: "cargo",
    name: "Cargo",
    description: "The Rust package manager — build, test, document, benchmark, and publish Rust projects.",
    githubOwner: "rust-lang",
    githubRepo: "cargo",
    websiteUrl: "https://doc.rust-lang.org/cargo",
    categories: ["package-managers"],
  },
  {
    slug: "yarn",
    name: "Yarn",
    description: "Fast, reliable, secure dependency management — Yarn Berry with Plug'n'Play and zero-installs.",
    githubOwner: "yarnpkg",
    githubRepo: "yarn",
    websiteUrl: "https://yarnpkg.com",
    brewName: "yarn",
    categories: ["package-managers"],
  },

  // ── SEARCH ─────────────────────────────────────────────────────────────────
  {
    slug: "ripgrep",
    name: "ripgrep",
    description: "Recursively searches directories for a regex pattern, faster than grep, respects .gitignore.",
    githubOwner: "BurntSushi",
    githubRepo: "ripgrep",
    brewName: "ripgrep",
    categories: ["search"],
    featured: true,
  },
  {
    slug: "fzf",
    name: "fzf",
    description: "A command-line fuzzy finder — pipes into any list to instantly filter and select.",
    githubOwner: "junegunn",
    githubRepo: "fzf",
    brewName: "fzf",
    categories: ["search"],
    featured: true,
  },
  {
    slug: "fd",
    name: "fd",
    description: "A simple, fast and user-friendly alternative to find.",
    githubOwner: "sharkdp",
    githubRepo: "fd",
    brewName: "fd",
    categories: ["search"],
  },
  {
    slug: "the-silver-searcher",
    name: "ag",
    description: "A code searching tool similar to ack, with a focus on speed.",
    githubOwner: "ggreer",
    githubRepo: "the_silver_searcher",
    brewName: "the_silver_searcher",
    categories: ["search"],
  },

  // ── FILES ──────────────────────────────────────────────────────────────────
  {
    slug: "bat",
    name: "bat",
    description: "A cat clone with syntax highlighting and Git integration.",
    githubOwner: "sharkdp",
    githubRepo: "bat",
    brewName: "bat",
    categories: ["files"],
    featured: true,
  },
  {
    slug: "eza",
    name: "eza",
    description: "A modern, maintained replacement for ls — colors, icons, git status, and tree view.",
    githubOwner: "eza-community",
    githubRepo: "eza",
    brewName: "eza",
    categories: ["files"],
  },
  {
    slug: "yazi",
    name: "yazi",
    description: "Blazing fast terminal file manager written in Rust — async I/O, previews, and plugin system.",
    githubOwner: "sxyazi",
    githubRepo: "yazi",
    brewName: "yazi",
    categories: ["files"],
  },
  {
    slug: "broot",
    name: "broot",
    description: "A new way to see and navigate directory trees — instant search, fuzzy matching, and shell integration.",
    githubOwner: "Canop",
    githubRepo: "broot",
    brewName: "broot",
    categories: ["files"],
  },

  // ── SYSTEM ─────────────────────────────────────────────────────────────────
  {
    slug: "btop",
    name: "btop",
    description: "Resource monitor showing usage and stats for CPU, memory, disks, network, and processes — beautiful TUI.",
    githubOwner: "aristocratos",
    githubRepo: "btop",
    brewName: "btop",
    categories: ["system"],
    featured: true,
  },
  {
    slug: "bottom",
    name: "bottom",
    description: "Yet another cross-platform graphical process/system monitor written in Rust.",
    githubOwner: "ClementTsang",
    githubRepo: "bottom",
    brewName: "bottom",
    categories: ["system"],
  },
  {
    slug: "dust",
    name: "dust",
    description: "A more intuitive version of du written in Rust — shows disk usage visually.",
    githubOwner: "bootandy",
    githubRepo: "dust",
    brewName: "dust",
    categories: ["system"],
  },
  {
    slug: "duf",
    name: "duf",
    description: "Disk Usage/Free Utility — beautiful df replacement with colors and sorting.",
    githubOwner: "muesli",
    githubRepo: "duf",
    brewName: "duf",
    categories: ["system"],
  },
  {
    slug: "procs",
    name: "procs",
    description: "A modern replacement for ps written in Rust — colored, paged output with search.",
    githubOwner: "dalance",
    githubRepo: "procs",
    brewName: "procs",
    categories: ["system"],
  },

  // ── NETWORK ────────────────────────────────────────────────────────────────
  {
    slug: "httpie",
    name: "HTTPie",
    description: "Modern, user-friendly command-line HTTP client — colorized output, JSON, sessions, plugins.",
    githubOwner: "httpie",
    githubRepo: "cli",
    brewName: "httpie",
    categories: ["network"],
  },
  {
    slug: "xh",
    name: "xh",
    description: "Friendly and fast tool for sending HTTP requests — HTTPie-compatible, written in Rust.",
    githubOwner: "ducaale",
    githubRepo: "xh",
    brewName: "xh",
    categories: ["network"],
  },
  {
    slug: "gping",
    name: "gping",
    description: "Ping, but with a graph — visualize latency over time in the terminal.",
    githubOwner: "orf",
    githubRepo: "gping",
    brewName: "gping",
    categories: ["network"],
  },
  {
    slug: "dog",
    name: "dog",
    description: "A command-line DNS client with colorized output and support for DNS-over-HTTPS.",
    githubOwner: "ogham",
    githubRepo: "dog",
    brewName: "dog",
    categories: ["network"],
  },

  // ── PRODUCTIVITY ───────────────────────────────────────────────────────────
  {
    slug: "just",
    name: "just",
    description: "A handy way to save and run project-specific commands — like make but sane.",
    githubOwner: "casey",
    githubRepo: "just",
    brewName: "just",
    categories: ["productivity"],
    featured: true,
  },
  {
    slug: "hyperfine",
    name: "hyperfine",
    description: "A command-line benchmarking tool — statistical analysis, warmup runs, and export results.",
    githubOwner: "sharkdp",
    githubRepo: "hyperfine",
    brewName: "hyperfine",
    categories: ["productivity"],
  },
  {
    slug: "tldr",
    name: "tldr",
    description: "Simplified, community-driven man pages — practical examples instead of dense manuals.",
    githubOwner: "tldr-pages",
    githubRepo: "tldr",
    brewName: "tldr",
    categories: ["productivity"],
  },
  {
    slug: "tokei",
    name: "tokei",
    description: "Count your code quickly — lines of code, comments, blanks per language across a codebase.",
    githubOwner: "XAMPPRocky",
    githubRepo: "tokei",
    brewName: "tokei",
    categories: ["productivity"],
  },
  {
    slug: "direnv",
    name: "direnv",
    description: "Load and unload environment variables depending on the current directory.",
    githubOwner: "direnv",
    githubRepo: "direnv",
    brewName: "direnv",
    categories: ["productivity"],
  },

  // ── TEXT ───────────────────────────────────────────────────────────────────
  {
    slug: "jq",
    name: "jq",
    description: "Lightweight and flexible command-line JSON processor — the swiss army knife of JSON.",
    githubOwner: "jqlang",
    githubRepo: "jq",
    brewName: "jq",
    categories: ["text"],
    featured: true,
  },
  {
    slug: "yq",
    name: "yq",
    description: "Process YAML, JSON, XML, CSV and properties documents from the CLI.",
    githubOwner: "mikefarah",
    githubRepo: "yq",
    brewName: "yq",
    categories: ["text"],
  },
  {
    slug: "fx",
    name: "fx",
    description: "Terminal JSON viewer and processor — interactive exploration with JavaScript expressions.",
    githubOwner: "antonmedv",
    githubRepo: "fx",
    brewName: "fx",
    categories: ["text"],
  },
  {
    slug: "sd",
    name: "sd",
    description: "Intuitive find & replace CLI — a simpler, faster sed alternative.",
    githubOwner: "chmln",
    githubRepo: "sd",
    brewName: "sd",
    categories: ["text"],
  },
];

export const CURATED_CATEGORIES = [
  // AI first
  { slug: "ai-models",        label: "AI Models",         iconName: "Sparkles",    sortOrder: 1  },
  { slug: "ai-coding",        label: "AI Coding",         iconName: "Bot",         sortOrder: 2  },
  // Dev environment
  { slug: "editors",          label: "Editors & IDEs",    iconName: "Code",        sortOrder: 3  },
  { slug: "terminals",        label: "Terminals",         iconName: "Monitor",     sortOrder: 4  },
  { slug: "shells",           label: "Shells",            iconName: "Hash",        sortOrder: 5  },
  // Platform & infra
  { slug: "version-control",  label: "Version Control",   iconName: "GitBranch",   sortOrder: 6  },
  { slug: "hosting",          label: "Hosting & Cloud",   iconName: "Cloud",       sortOrder: 7  },
  { slug: "containers",       label: "Containers",        iconName: "Box",         sortOrder: 8  },
  { slug: "kubernetes",       label: "Kubernetes",        iconName: "Layers",      sortOrder: 9  },
  // Dev tooling
  { slug: "git",              label: "Git CLI",           iconName: "GitCommit",   sortOrder: 10 },
  { slug: "package-managers", label: "Package Managers",  iconName: "Package",     sortOrder: 11 },
  // CLI tools
  { slug: "search",           label: "Search",            iconName: "Search",      sortOrder: 12 },
  { slug: "files",            label: "Files",             iconName: "FolderOpen",  sortOrder: 13 },
  { slug: "text",             label: "Text & Data",       iconName: "FileText",    sortOrder: 14 },
  { slug: "system",           label: "System",            iconName: "Cpu",         sortOrder: 15 },
  { slug: "network",          label: "Network",           iconName: "Wifi",        sortOrder: 16 },
  { slug: "productivity",     label: "Productivity",      iconName: "Zap",         sortOrder: 17 },
];
